name:                haskell-raytracer
version:             0.1.0.0
github:              "DmitryRotay/haskell-raytracer"
license:             BSD3
author:              "Dmitry Rotay"
maintainer:          "dmitry.rotay@gmail.com"
copyright:           "2020 Dmitry Rotay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-raytracer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-raytracer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-raytracer

tests:
  haskell-raytracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-raytracer
    - hspec
    - hspec-discover
    - QuickCheck
